
#ifndef ___UTILIY__ITERATOR__EXTRA___
#define ___UTILIY__ITERATOR__EXTRA___

#ifdef UTILITY_ITERATOR_HAS_EXTRA

#define UTILITY_ITERATOR_HAS_EXTRA_OPERATOR_ADD true

#endif // ! UTILITY_ITERATOR_HAS_EXTRA

#endif // ! ___UTILIY__ITERATOR__EXTRA___
