
#ifndef __UTILITY_TRAIT_TYPE_FEATURES_IS_NOTHROW_INVOCABLE_R__
#define __UTILITY_TRAIT_TYPE_FEATURES_IS_NOTHROW_INVOCABLE_R__

#include<utility/trait/type/features/is_invocable.hpp>

#endif // ! __UTILITY_TRAIT_TYPE_FEATURES_IS_NOTHROW_INVOCABLE_R__
