
#ifndef ___UTILITY__ALGORITHM__EXTRA__
#define ___UTILITY__ALGORITHM__EXTRA__

#ifdef UTILITY_ALGORITHM_NEED_EXTRA

#define UTILITY_ALGORITHM_SORT_HAS_EXTRA true

#endif // ! UTILITY_ALGORITHM_NEED_EXTRA

#endif // ! ___UTILITY__ALGORITHM__EXTRA__
